### ISSUE TITLE
Lazy serial data polling

### ISSUE THREAD

**Issue by FrankLaterza** [FrankLaterza/eta_space_serial#2]
Currently, the serial buffer is being serviced every 25ms. This solution can be made more robust by switching to an async serial data interrupt that updates the front end. Essentially the backend will tell the frontend to update when it has new data.

**Comment by FrankLaterza** [comment]
frontend information is now updated by the backend

**Comment by bastian2001** [comment]
Hi Frank, do you mind pointing me to the changes you made in order to call a JS/TS function from the Rust backend?

**Comment by FrankLaterza** [comment]
Of course! I opened a discussion in the tauri repo that might help [here](https://github.com/tauri-apps/tauri/discussions/7558). All you need to do is get the app handle and emit a event call to js. Lmk if you have anymore questions!
